### 條件1
#### 使用者評論數大於2

In [1]:
import pandas as pd
import os 
import statsmodels.api as sm
df=pd.read_csv('userstar.csv')

In [2]:
df

,BOOKNAME,CONTENT,ISBN,USER,USERSTAR
0,「氣內臟」自癒按摩法：每天按摩脾．肝．腎30秒，美肌、消除便秘、好眠、減肥，天天都有好氣色！,深入淺出，圖片清晰介唔按壓身體及伸展。\n按照個人體質、情志、節氣等，以吃，嗅香芬、調息、伸...,9789865683498,啟迪,5.0
1,唐鳳：我所看待的自由與未來,一開始是對唐鳳好奇，想更了解她，讀完之後真正體認到她是個傳奇人物，同時她的家庭給了她很大的自...,9789575036942,Miley Guan,5.0
2,老夫老妻重返青春（1）,看了很暖心的漫畫，會覺得要好好過每一天,9789865241810,蘇蘇,0.0
3,祕密瑜伽士的日常,直指心性的好書，書中道理發人省思,9789864779079,kbboss7416,5.0
4,花開千年（01）,好唯美的畫風。喜歡故事開頭引用的一段《佛經》：「彼岸花，開一千年，落一千年，花葉永不想見。情...,9789571068121,Annie,5.0
...,...,...,...,...,...
100429,劍魂如初3,竟然還沒有完結 ! 期待續集,9789861337142,麻糬看書不挑食,5.0
100430,響～成為小說家的方法～(02),很特別的女孩，很特別的故事,9789571084886,麻糬看書不挑食,5.0
100431,住院醫生PGY（一）,超級寫實的醫學漫畫,9789866081163,麻糬看書不挑食,5.0
100432,藍色時期 (7),達成目標不是終點,9789572679166,麻糬看書不挑食,5.0
100433,劍魂如初2：山河如故,雖然讓人聯想到「暮光之城」，但是好看,9789861336763,麻糬看書不挑食,5.0

In [3]:
df=df.dropna(axis=0)  # 刪除空值

In [4]:
df=df.drop(df[df["ISBN"]=='0'].index,axis=0)   # 刪除 ISBN等於 0

In [5]:
#df.loc[df['USERSTAR']==0,'USERSTAR']=float(1.0)    # 評分為 0 分給予 1 分

In [6]:
df['ISBN'] = df['ISBN'].astype('str')  # 確認 ISBN 為 STR
df['USERSTAR'] = df['USERSTAR'].astype('float64')  # 確認USERSTAR 為 float64

In [7]:
df_star=df
df_star

,BOOKNAME,CONTENT,ISBN,USER,USERSTAR
0,「氣內臟」自癒按摩法：每天按摩脾．肝．腎30秒，美肌、消除便秘、好眠、減肥，天天都有好氣色！,深入淺出，圖片清晰介唔按壓身體及伸展。\n按照個人體質、情志、節氣等，以吃，嗅香芬、調息、伸...,9789865683498,啟迪,5.0
1,唐鳳：我所看待的自由與未來,一開始是對唐鳳好奇，想更了解她，讀完之後真正體認到她是個傳奇人物，同時她的家庭給了她很大的自...,9789575036942,Miley Guan,5.0
2,老夫老妻重返青春（1）,看了很暖心的漫畫，會覺得要好好過每一天,9789865241810,蘇蘇,0.0
3,祕密瑜伽士的日常,直指心性的好書，書中道理發人省思,9789864779079,kbboss7416,5.0
4,花開千年（01）,好唯美的畫風。喜歡故事開頭引用的一段《佛經》：「彼岸花，開一千年，落一千年，花葉永不想見。情...,9789571068121,Annie,5.0
...,...,...,...,...,...
100429,劍魂如初3,竟然還沒有完結 ! 期待續集,9789861337142,麻糬看書不挑食,5.0
100430,響～成為小說家的方法～(02),很特別的女孩，很特別的故事,9789571084886,麻糬看書不挑食,5.0
100431,住院醫生PGY（一）,超級寫實的醫學漫畫,9789866081163,麻糬看書不挑食,5.0
100432,藍色時期 (7),達成目標不是終點,9789572679166,麻糬看書不挑食,5.0
100433,劍魂如初2：山河如故,雖然讓人聯想到「暮光之城」，但是好看,9789861336763,麻糬看書不挑食,5.0

In [8]:
#評論數大於2 抓出
df_star=df_star.groupby('USER').filter(lambda x : len(x)>1)
df_star=df_star.reset_index(drop=True)

In [9]:
df_star['user_id'] = pd.Categorical(df_star.USER).codes

In [10]:
df_star=df_star.sort_values(by=['user_id']) # 為使用者上ID
df_star

,BOOKNAME,CONTENT,ISBN,USER,USERSTAR,user_id
23593,別讓我走,一個淡淡悲傷的故事。\n整體的氛圍是朦朧有如在霧中視物，凱西第一人稱的敘事方式十分瑣碎，回憶...,9789861247816,Lily,5.0,0
22139,中華秩序,本書從地理（與主要是）歷史角度分析中國/中華秩序的本質，以及中華秩序對世界的影響（與/或危害...,9789578654365,Lily,5.0,0
22477,陳澄波密碼,有趣的作品，透過發現畫作不自然之處然後追尋、解謎的過程讓人想起達文西密碼。看完小說會想再找時...,9789573283928,Lily,4.0,0
14133,深入最禁忌的消化道之旅,非常有趣的一本書，作者幽默風趣的筆法令人捧腹大笑\n看完這本跟NASA那本書以後，我確定了以...,9789864798056,Lily,0.0,0
16350,花開時節,背景設定在日治時期的台中，主角楊馨儀因為失足落水所以穿越，成為日治時期大戶人家楊家最小的千金...,9789869538718,Lily,4.0,0
...,...,...,...,...,...,...
14246,想見你 Someday or one day：原著小說,這個故事的題材很特別，融合推理、愛情、平行時空等元素。\n\n故事的緣起是因為黃雨萱太想見到...,9789869811750,＜＞＜,5.0,4079
69151,CIA洗腦計畫：解密美國史上最暗黑的心智操控實驗,我是因為犯罪才坐牢的，但我覺得他們對我做的事比我犯的罪更惡劣。\n──詹姆斯．「白佬」．巴爾...,9789869891387,＜＞＜,5.0,4079
17966,亞森‧羅蘋冒險系列5：怪盜與名偵探(平裝),不得不說莫里斯早期的角色個性設定真的很討人厭，書中的福爾摩斯只是一個空有虛名、自以為是的草包...,9789861781716,＜＞＜,3.0,4079
17962,殺戒3：玄鐘,看完三部曲，真的會讓人廢寢忘食的一部作品！\n每個正派角色都好討人喜歡，作者對男性角色特別殘...,9789869861786,＜＞＜,5.0,4079
63921,有一間咖啡廳（典藏版）,蝶大早期的書我真是水土不服～\n\n書中一直沒有交代女主角沈靜的背景與過往經歷，因此讓我很難...,9789866277702,＜＞＜,3.0,4079

In [11]:
df_starpivot = df_star.pivot_table(index='user_id', columns='ISBN', values='USERSTAR')
df_starpivot

ISBN,1905302050014,1907082050017,4710415386243,4710614360792,4710614360808,4710614360815,4710614369702,4710614370388,4710614370579,4710614371385,...,9867600797,986774893X,9867881338,9867975634,9868231779,9879862291597,9991070427013,9991080725024,9991080725031,9999000914138
user_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_newpivot= df_starpivot.fillna(float(0))  # 空值補 0

In [13]:
to_array=df_newpivot.values   # 轉成向量
to_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
users=df_newpivot.index.astype('int').max()   # 轉型別
userid=[i for i in range(users+1)]

In [15]:
from sklearn.metrics.pairwise import cosine_similarity   # 餘絃相似度
cos_sims = cosine_similarity(to_array)
sims_df=pd.DataFrame(cos_sims,columns=userid,index=userid)
sims_df

,0,1,2,3,4,5,6,7,8,9,...,4070,4071,4072,4073,4074,4075,4076,4077,4078,4079
0,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.041561,0.0,0.0,0.0,0.0
2,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4075,0.0,0.041561,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.050299,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.0
4076,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,1.0,0.0,0.0,0.0
4077,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,1.0,0.0,0.0
4078,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,1.0,0.0
4079,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,1.0

## 兩使用者所看的書

In [16]:
sims_df.iloc[:,33].nlargest(2) # userid=33 的使用者 相似前兩名 第一為自己

33      1.000000
3204    0.505076
Name: 33, dtype: float64

In [17]:
df_star.loc[df_star['user_id']==33][:] # 自己看過的書

,BOOKNAME,CONTENT,ISBN,USER,USERSTAR,user_id
66813,TOO BIG TO KNOW,"在網路發達資訊爆炸的年代，過去傳統的知識傳遞與架構正經歷翻天覆地的改變,\n有的人預言這將造...",9789862622025,97252013,5.0,33
66792,"無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代",作者用了許多大家評論或敘述文學藝術哲學之存在價值，讓讀者去反思在現代社會中所崇尚經濟邏輯下的...,9789865671723,97252013,4.0,33
66810,從0到1,打破一般傳統工業邏輯思維，不強調快速複製的技術，只追求能夠打破世界秩序與市場需求的破壞式創新...,9789862419533,97252013,4.0,33
66811,人類大歷史,歷史敘述結合哲學、經濟學已經不稀奇了，但本書除此之外更從人類學、考古學、科技史學等角度進行切...,9789863205449,97252013,5.0,33
66803,異鄉人,在喧囂的人群佇足，或許可以假裝自己是個社會化成熟的大人\n看著群眾此起彼落的攻訐，仔細聆聽試...,9789861735450,97252013,4.0,33

In [18]:
df_star.loc[df_star['user_id']==1516][:] # 對方看過的書

,BOOKNAME,CONTENT,ISBN,USER,USERSTAR,user_id
20243,麒麟之翼,一如過往的加賀恭一郎系列，在尋找凶案真相過程中，扣連到疏離的家庭，嗜血的媒體，派遣人員的不公...,9789866043345,evava,4.0,1516
32205,起源,丹．布朗的羅柏·蘭登系列所探討的題材每每有驚喜，這次也不例外，選取了具爭議性的題材──人類的...,9789571373867,evava,5.0,1516

In [19]:
sims_df.iloc[:,5].nlargest(5).index # user_id = 5 相似的前五名  第一名為自己

Int64Index([5, 4039, 481, 565, 665], dtype='int64')

In [20]:
df_star.loc[df_star.user_id==5]['BOOKNAME'] # user_id = 5 看的書

8437            關係黑洞：面對侵蝕關係的不安全感，我們該如何救贖自己？
8441                      兩個女人住一起：非關愛情的同居時代
16356                                 女神自助餐
15764                          致不在場的他們與遲到的我
15655                         李智雅姊姊，現在終於能說了
15649               破碎之海Ⅰ：半王的復仇 Half a King
15646                                我們沒有祕密
15645    燈塔行（吳爾芙經典傳世之作，出版91周年雙面海報燙銀書衣典藏紀念版）
15642                          破碎之海Ⅱ：劍魂的試煉
15531                                 莫斯科紳士
15529                                  如膚之深
15516                           破碎之海Ⅲ：權力的灰燼
15421                               明天別再來敲門
9485                     過度努力：每個「過度」，都是傷的證明
Name: BOOKNAME, dtype: object

In [21]:
df_star.loc[df_star.user_id==3962]['BOOKNAME'] # user_id= 3962 看的書 * 發現都看過莫斯科的紳士這本書

10097                  半澤喵樹(01)
12347                      蟲師 1
13153                     午夜圖書館
8361                         邪臨
9067          一不小心就和魔法師契約結婚了（1）
                  ...
16787                     傲慢與善良
12017                     大港的女兒
63787            爸爸與父親的家庭食堂(03)
16785    Dr. Dmat ~ 瓦礫下的醫師 ~(1)
53552                      誰殺了她
Name: BOOKNAME, Length: 226, dtype: object

In [22]:
sims_df.iloc[:,33].nlargest(4)  # user_id 33 和 1516 相似度接近一

33      1.000000
3204    0.505076
1250    0.433099
3233    0.433099
Name: 33, dtype: float64

In [23]:
# 取出 user_id 和 similarity 做成 list
sim_scores=list(sims_df.iloc[:,33].nlargest(5))
# 與 user_id 與 其他使用者的相似度
sim_users=list(sims_df.iloc[:,33].nlargest(5).index)
print(sim_users)
sim_scores

[33, 3204, 1250, 3233, 3073]

[1.0000000000000002,
 0.5050762722761054,
 0.43309933042202314,
 0.43309933042202314,
 0.3943983074101663]

In [24]:
# 丟入dictionary
sims_dict={}
for i in range(1,5):
    sims_dict[str(sim_users[i])]=sim_scores[i]
print(sims_dict)

{'3204': 0.5050762722761054, '1250': 0.43309933042202314, '3233': 0.43309933042202314, '3073': 0.3943983074101663}

In [25]:
# 比對差集(雙方沒有交集的書籍) 減 自己看過的書 = 對方和自己沒交集的書
own=list(df_star.loc[df_star.user_id==33]['BOOKNAME'])
print(own)
for k,v in sims_dict.items():
    the_other=list(df_star.loc[df_star.user_id==int(k)]['BOOKNAME'])
    print(f'還可以看{set(the_other)-set(own)}，讀者{k}相似度{v:.2f}')
    print()

['TOO BIG TO KNOW', '無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代', '從0到1', '人類大歷史', '異鄉人']
還可以看{'一流的人讀書，都在哪裡畫線？'}，讀者3204相似度0.51

還可以看{'文明更迭的源代碼'}，讀者1250相似度0.43

還可以看{'正妹心理學'}，讀者3233相似度0.43

還可以看{'惡血'}，讀者3073相似度0.39

In [26]:
# 做出 丟入 user_id 的號碼 ， 抓出前五大similartiy 沒有看過的書
userid=1

while userid!='':
    userid=input('enter userid:(print enter to end) ')
    if userid=='':
        break
    userid=int(userid)
    make_sure=list(sims_df.iloc[:,userid].nlargest(5).index)
    x=make_sure[0]
    y=make_sure[1]
    print('相似使用者:',y)
    own=list(df_star.loc[df_star.user_id==x]['BOOKNAME'])
    print(f'{x}看了{own}')
    the_other=list(df_star.loc[df_star.user_id==y]['BOOKNAME'])
    print(f'{y}看了{the_other}')
    book_n=0
    book_un=0
    for i in own:
        if i in the_other:
            book_n+=1
            print(i,'相同')
    print('共相同:',book_n,'本書')
    print('還可以看:',set(own) ^ set(the_other))

enter userid:(print enter to end) 33
相似使用者: 3204
33看了['TOO BIG TO KNOW', '無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代', '從0到1', '人類大歷史', '異鄉人']
3204看了['一流的人讀書，都在哪裡畫線？', '人類大歷史']
人類大歷史 相同
共相同: 1 本書
還可以看: {'TOO BIG TO KNOW', '無用之用: 醞釀之必要, 徒然之必要, 歡迎來到無用時代', '一流的人讀書，都在哪裡畫線？', '異鄉人', '從0到1'}
enter userid:(print enter to end)

## 後缺: 
+ 類別推書(K-means)
+ 列出分數較高的書籍(coding)
+ 預測使用者給的分數(knn?)